-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgkIrLyg6Ib8hPlyx4
P7n+R2D8WVAgrQkAmxbGlvzKZF6gCgYIKoZIzj0DAQehRANCAASa+2bTUA/9dKN1
YNBZHa+BOUs8DGYnlSYZ7jwk8/uDAbQdOWJRbgjBT4NeHJOu7tXFQpHNoq04Z2Zn
DAlj65yF
-----END PRIVATE KEY-----